using UnityEngine;
using System.Collections;
using UnityEngine.UI;
using System.Collections.Generic;
using System.IO;

public class TypingSoft : MonoBehaviour
{
    [SerializeField] private float _timeLimit = 3.0f;

    //ï¿½@ï¿½ï¿½ï¿½Ì“ï¿½ï¿½{ï¿½ê•¶
    private string[] qJ = { "ï¿½ï¿½ï¿½", "ï¿½eï¿½Xï¿½g", "ï¿½^ï¿½Cï¿½sï¿½ï¿½ï¿½O", "ï¿½ï¿½ï¿½ß‚ï¿½ï¿½ß‚ï¿½ï¿½ï¿½ï¿½" };
    //ï¿½@ï¿½ï¿½ï¿½Ìƒï¿½ï¿½[ï¿½}ï¿½ï¿½ï¿½ï¿½
    private string[] qR = { "monndai", "tesuto", "taipinngu", "kamekumechann" };
    //ï¿½@ï¿½ï¿½ï¿½{ï¿½ï¿½\ï¿½ï¿½ï¿½eï¿½Lï¿½Xï¿½g
    private Text UIJ;
    //ï¿½@ï¿½ï¿½ï¿½[ï¿½}ï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½eï¿½Lï¿½Xï¿½g
    private Text UIR;
    //ï¿½@ï¿½ï¿½ï¿½{ï¿½ï¿½ï¿½ï¿½
    private string nQJ;
    //ï¿½@ï¿½ï¿½ï¿½[ï¿½}ï¿½ï¿½ï¿½ï¿½ï¿½
    private string nQR;
    //ï¿½@ï¿½ï¿½ï¿½Ôï¿½
    private int numberOfQuestion;
    //ï¿½@ï¿½ï¿½ï¿½Ì‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ú‚ï¿½
    private int indexOfString;

    //ï¿½@ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½Lï¿½Xï¿½g
    private Text UII;
    //ï¿½@ï¿½ï¿½ï¿½ï¿½
    private int correctN;
    //ï¿½@ï¿½ï¿½ï¿½ğ”•\ï¿½ï¿½ï¿½pï¿½eï¿½Lï¿½Xï¿½gUI
    private Text UIcorrectA;
    //ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
    private string correctString;

    //ï¿½@ï¿½ï¿½ï¿½sï¿½ï¿½
    private int mistakeN;
    //ï¿½@ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½pï¿½eï¿½Lï¿½Xï¿½gUI
    private Text UImistake;

    //ï¿½@ï¿½ï¿½ï¿½ï¿½
    private float correctAR;
    //ï¿½@ï¿½ï¿½ï¿½ğ—¦•\ï¿½ï¿½ï¿½pï¿½eï¿½Lï¿½Xï¿½gUI
    private Text UIcorrectAR;

    // ï¿½ï¿½ï¿½tï¿½@ï¿½Cï¿½ï¿½ï¿½pï¿½X
    [SerializeField] private string _textFilePath;

    [SerializeField] private SerihuSpawner _serihuSpawner;

    // ï¿½ï¿½ï¿½iï¿½[ï¿½Ïï¿½
    private List<string> _japaneseQuestion = new List<string>();
    private List<string> _romeQuestion = new List<string>();

    // ï¿½ï¿½ï¿½ÔŒvï¿½ï¿½
    private float _time = 0.0f;

    private int exclamationMarkCount = 0;

    public bool resetPositionFlag = false;

    public bool stopFlag = false;

    private bool _inputCompleted = false; 

    void Start()
    {
        LoadTextFile();

        //ï¿½@ï¿½eï¿½Lï¿½Xï¿½gUIï¿½ï¿½ï¿½æ“¾
        UIJ = transform.Find("InputPanel/QuestionJ").GetComponent<Text>();
        UIR = transform.Find("InputPanel/QuestionR").GetComponent<Text>();
        UII = transform.Find("InputPanel/Input").GetComponent<Text>();
        UIcorrectA = transform.Find("DataPanel/Correct Answer").GetComponent<Text>();
        UImistake = transform.Find("DataPanel/Mistake").GetComponent<Text>();
        UIcorrectAR = transform.Find("DataPanel/Correct Answer Rate").GetComponent<Text>();

        //ï¿½@ï¿½fï¿½[ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        correctN = 0;
        UIcorrectA.text = correctN.ToString();
        mistakeN = 0;
        UImistake.text = mistakeN.ToString();
        correctAR = 0;
        UIcorrectAR.text = correctAR.ToString();

        //ï¿½@ï¿½ï¿½ï¿½oï¿½Íƒï¿½ï¿½\ï¿½bï¿½hï¿½ï¿½ï¿½Ä‚ï¿½
        OutputQ();

        // ï¿½Ïï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        _time = 0.0f;

        resetPositionFlag = false;

        //stopFlag = false;

        _inputCompleted = false;
    }

    private void LoadTextFile()
    {
        int count = 0;
        // ï¿½ï¿½sï¿½ï¿½ï¿½Â“Ç‚İï¿½ï¿½ï¿½
        using (var fs = new StreamReader(Application.dataPath + "/test.txt", System.Text.Encoding.GetEncoding("UTF-8")))
        {
            while (fs.Peek() != -1)
            {
                if(count % 2 == 0)
                {
                    _japaneseQuestion.Add(fs.ReadLine());
                }
                else
                {
                    _romeQuestion.Add(fs.ReadLine());
                }

                count++;
            }

        }
    }

    //ï¿½@ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½éƒï¿½\ï¿½bï¿½h
    void OutputQ()
    {
        //ï¿½@ï¿½eï¿½Lï¿½Xï¿½gUIï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        UIJ.text = "";
        UIR.text = "";
        UII.text = "";

        //ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        correctString = "";
        //ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½ÌˆÊ’uï¿½ï¿½0ï¿½Ô–Ú‚É–ß‚ï¿½
        indexOfString = 0;

        //ï¿½@ï¿½ï¿½è”ï¿½ï¿½ï¿½Åƒï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½É‘Iï¿½ï¿½
        numberOfQuestion = Random.Range(0, _japaneseQuestion.Count);

        //ï¿½@ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½Lï¿½Xï¿½gUIï¿½ÉƒZï¿½bï¿½g
        nQJ = _japaneseQuestion[numberOfQuestion] ;
        nQR = _romeQuestion[numberOfQuestion];

        //ï¿½@ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½eï¿½Lï¿½Xï¿½gUIï¿½ÉƒZï¿½bï¿½g

        UIJ.text = _japaneseQuestion[numberOfQuestion];
        UIR.text = _romeQuestion[numberOfQuestion];

        // ï¿½ï¿½ï¿½Ô‚ï¿½ß‚ï¿½
        _time = 0.0f;
        _inputCompleted = false;
        resetPositionFlag = true;
    }

    void Update()
    {
        if(stopFlag == false)
        {
            UIJ.enabled = true;
            UIR.enabled = true;

            _time += Time.deltaTime;
        }
        else
        {
            UIJ.enabled = false;
            UIR.enabled = false;
        }


        if (_inputCompleted == true && _timeLimit > _time)
        {
            ExclamationMarkCount();

            return;
        }
        else if(_inputCompleted == true && _timeLimit <= _time)
        {
            var serihu = _japaneseQuestion[numberOfQuestion];
            for (int i = 0; i < exclamationMarkCount; i++)
            {
                serihu += "!";
            }

            exclamationMarkCount = 0;

            // ï¿½Zï¿½ï¿½ï¿½tï¿½ï¿½ï¿½ï¿½
            _serihuSpawner.Spawn(serihu);

            OutputQ();

            Debug.Log(_time);

            stopFlag = true;

            return;
        }
        //if (stopFlag == true)
        //{

        //    UIJ.enabled = false;
        //    UIR.enabled = false;
        //    return;
        //}

        //ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é•¶ï¿½ï¿½ï¿½ÆƒLï¿½[ï¿½{ï¿½[ï¿½hï¿½ï¿½ï¿½ï¿½Å‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ç‚ï¿½ï¿½ï¿½
        if (Input.GetKeyDown(nQR[indexOfString].ToString()))
        {
            //ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚Ñoï¿½ï¿½
            Correct();

                //ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½çŸï¿½Ì–ï¿½ï¿½ï¿½\ï¿½ï¿½
            if (indexOfString >= nQR.Length)
            {
                _inputCompleted = true;

                //// ï¿½Zï¿½ï¿½ï¿½tï¿½ï¿½ï¿½ï¿½
                //_serihuSpawner.Spawn(_japaneseQuestion[numberOfQuestion]);

                //OutputQ();

                //stopFlag = true;
            }
        }
        else if (Input.anyKeyDown)
        {
            //ï¿½@ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚Ñoï¿½ï¿½
            Mistake();
        }

        // ï¿½ï¿½ï¿½ï¿½
        MesureTime();
    }

    //ï¿½@ï¿½^ï¿½Cï¿½sï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
    void Correct()
    {
        //ï¿½@ï¿½ï¿½ï¿½ğ”‚ğ‘‚â‚·
        correctN++;
        UIcorrectA.text = correctN.ToString();
        //ï¿½@ï¿½ï¿½ï¿½ğ—¦‚ÌŒvï¿½Z
        CorrectAnswerRate();
        //ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½
        correctString += nQR[indexOfString].ToString();
        UII.text = correctString;
        //ï¿½@ï¿½ï¿½ï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½wï¿½ï¿½
        indexOfString++;
    }

    //ï¿½@ï¿½^ï¿½Cï¿½sï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½sï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½
    void Mistake()
    {
        //ï¿½@ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ğ‘‚â‚·ï¿½iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½Î‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½j
        mistakeN += Input.inputString.Length;

        UImistake.text = mistakeN.ToString();
        //ï¿½@ï¿½ï¿½ï¿½ğ—¦‚ÌŒvï¿½Z
        CorrectAnswerRate();
        //ï¿½@ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½
        if (Input.inputString != "")
        {
            UII.text = correctString + "<color=#ff0000ff>" + Input.inputString + "</color>";
        }
    }

    //ï¿½@ï¿½ï¿½ï¿½ğ—¦‚ÌŒvï¿½Zï¿½ï¿½ï¿½ï¿½
    void CorrectAnswerRate()
    {
        //ï¿½@ï¿½ï¿½ï¿½ğ—¦‚ÌŒvï¿½Z
        correctAR = 100f * correctN / (correctN + mistakeN);
        //ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½È‰ï¿½ï¿½ÌŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½í‚¹ï¿½ï¿½
        UIcorrectAR.text = correctAR.ToString("0.00");
    }

    void MesureTime()
    {
        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½ß‚ï¿½ï¿½ï¿½ï¿½ï¿½
        if(_timeLimit < _time)
        {
            //ï¿½ï¿½ï¿½Ì•ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½
            OutputQ();
            Debug.Log(_time);
        }
    }

    public float GetTimeLimit() { return _timeLimit; }

    void ExclamationMarkCount()
    {
        if(Input.GetKeyDown(KeyCode.Alpha1))
        {
            correctString += "!";
            UII.text = correctString;
            exclamationMarkCount++;
        }
    }
}
